# Generated by Django 2.0.7 on 2018-07-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corrente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título Corrente')),
                ('corrente', models.TextField(max_length=5000, verbose_name='Corrente')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
            ],
            options={
                'verbose_name': 'Corrente',
                'verbose_name_plural': 'Correntes',
            },
        ),
    ]
